### ISSUE TITLE
Game crashing with invictus

### ISSUE THREAD

**Issue by mokamars** [SnowletTV/Invictus#188]
Seems to look at a folder that does not exists (gfx/skins)

[error.log](https://github.com/SnowletTV/Invictus/files/13546298/error.log)
[game.log](https://github.com/SnowletTV/Invictus/files/13546299/game.log)
[system.log](https://github.com/SnowletTV/Invictus/files/13546300/system.log)
[debug.log](https://github.com/SnowletTV/Invictus/files/13546301/debug.log)

**Comment by RobbeVDK** [comment]
Can you try disabling Better UI

**Comment by mokamars** [comment]
I added the path in th mod file

**Comment by mokamars** [comment]
Sorry, It was the mod form nexus and not moddb. And you were rigth. I didn't susbscribed to the free dlc. It works now. Thanks for your help
